# Generated by Django 3.0 on 2021-01-01 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('course_provider_name', models.CharField(max_length=255)),
                ('img_of_course', models.ImageField(blank=True, null=True, upload_to='')),
                ('img_of_provider', models.ImageField(blank=True, null=True, upload_to='')),
                ('category', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
    ]
